# ArgoCD Application for NATS MCP Server (Warp)
# Deploy this to your ArgoCD namespace to enable GitOps
#
# Current deployment status:
#   - Namespace: nats-mcp
#   - NATS ClusterIP: nats.nats-mcp.svc:4222
#   - NATS External: 192.168.7.16:4222 (LoadBalancer)
#   - JetStream: Enabled with 10Gi storage
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-mcp
  namespace: argocd
spec:
  project: default
  source:
    # Gitea repository (private self-hosted)
    repoURL: https://gitea.vilo.network/ViLoHouse/nats-mcp-server.git
    targetRevision: main
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: nats-mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Repository secret for Gitea (if needed)
# Create this secret if ArgoCD cannot access the private Gitea repo
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gitea-nats-mcp-server
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://gitea.vilo.network/ViLoHouse/nats-mcp-server.git
#   username: <gitea-username>
#   password: <gitea-token>
